services:
  tilda:
    volumes:
      - ./seeds:/data/seeds/
    container_name: carts-mocker
    ports:
      - '8110:8110'
    environment:
      - PORT=8110
    image: ghcr.io/zzacal/tilda:v5.0.0-alpha
