version: '3.3'
services:
  tilda:
    volumes:
      - ./seed.json:/data/seed.json
      - ./seeds:/data/seeds/
    container_name: carts-mocker
    ports:
      - '8110:8110'
    environment:
      - PORT=8110
    image: ghcr.io/zzacal/tilda:latest
